src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=181)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Dday;

    /**
     * @ORM\Column(type="string", length=181)
     */
    private $adresse;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="createdEvents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $createur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDday(): ?\DateTimeInterface
    {
        return $this->Dday;
    }

    public function setDday(\DateTimeInterface $Dday): self
    {
        $this->Dday = $Dday;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreateur(): ?User
    {
        return $this->createur;
    }

    public function setCreateur(?User $createur): self
    {
        $this->createur = $createur;

        return $this;
    }
}

templates/showEvents/index.html.twig
{% extends "base.html.twig" %}
{% block title %}Organisation de mariages{% endblock %}
{% block body %}
    {% if events %}
        <table id="table" class="table table-striped">
            <thead>
            <tr>
                <th>Nom</th>
                <th>Dates</th>
                <th>Adresse</th>
                <th>Déscription</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
        {% for event in events %}
        <tr>
            <td>{{ event.name}}</td>
             <td>{{ event.dday|date('y-m-d') }}</td>
            <td>{{ event.adresse }}</td>
            <td>{{ event.description }}</td>

            <td>
                <a href="/event/1" class="btn btn-dark">Show</a>
            </td>
            <td>
                <a href="{{ path('delete_event',{'id':event.id})}}" class="btn btn-danger delete-event" data-id="{{ event.id }}">Delete</a>
            </td>
        </tr>
            {% endfor %}
            </tbody>


        </table>
{% else %}
        <p>pas de mariages dans les jours à venir !</p>
    {% endif %}
{% endblock %}
{% block javascripts %}
    <script src="/js/main.js"></script>
{% endblock %}